### PR TITLE
Fix caddy config #27

### PR DESCRIPTION
**Pull request by nexteve**

### CODE REVIEW

**Comment by wahyd4** [comment]
Thanks for your contribution, but unfortunately this pull request will be blocked due to we still couldn't download caddy with the `filebrowser` plugin.

By the way, a minor suggestion to you. Please add a more detailed description of what kind of issue you fixed.

**Comment by nexteve** [comment]
你好，这个仓库很棒，但我在使用时遇到了一些问题。
平台：x86
运行环境：群晖  =>  docker组件
在访问/ui 的应用AriaNG 时，会出现只加载了html，其他相关目录的静态资源全部404的情况，导致AriaNG无法正常工作。
我为caddyfile添加了这几条静态资源的配置后问题解决，所以提此PR希望能做一份贡献

**Comment by wahyd4** [comment]
Hi @nexteve, thanks again for your work. The AriaNg application supposed to be working under `/ui/` rather than `/ui`.
But I'm happy to consider the pull request you submitted. Moreover, as I mentioned above, this pull request needs to wait for further updates from Caddy.

**Comment by wahyd4** [comment]
Hi @nexteve, I've fixed the docker building issue, so could you please pull the updates from the master branch and then change the file accordingly? Thank you.

**Comment by wahyd4** [comment]
Due to the similar improvement from #37 has been merged, I will close this then

**Pull request closed without merging**
