### PR TITLE
Update arm64.Dockerfile

### PR DESCRIPTION
**Pull request by expoli**
update the rclone arm64 based download url

### CODE REVIEW

**Review by wahyd4 — APPROVED** [review]
Looks, thanks

**Comment by wahyd4** [comment]
@expoli The arm64 tag has been updated, please give a try.

**Comment by expoli** [comment]
Rclone can't start, It seems to be a permission problem, he is trying to write files in the root directory

```
aria2_1      | aria2c.1      | 11/25 06:52:00 [NOTICE] Serialized session to '/app/conf/aria2.session' successfully.
aria2_1      | usermod: no changes
aria2_1      | **** give caddy permissions to use low ports ****
aria2_1      | forego        | starting filebrowser.1 on port 5000
aria2_1      | forego        | starting caddy.1 on port 5100
aria2_1      | forego        | starting aria2c.1 on port 5300
aria2_1      | forego        | starting rclone.1 on port 5600
aria2_1      | caddy.1       | Run aria2c and ariaNG
aria2_1      | caddy.1       | Using caddy without Basic Auth
aria2_1      | rclone.1      | Start Rclone
aria2_1      | filebrowser.1 | 2020/11/25 06:52:05 No config file used
aria2_1      | filebrowser.1 | 2020/11/25 06:52:05 Listening on 127.0.0.1:8080
aria2_1      | rclone.1      | 2020/11/25 06:52:05 ERROR : error reading available plugins: Error creating : /root/.cache/rclone/webgui/plugins/config
```

**Comment by wahyd4** [comment]
Hi @expoli , this is normal the rclone complains about there is no such plugin in that folder, after this, it will try to download the plugin. 

Have you tried to hit the `/rclone` from your browser to see if it works?

**Comment by expoli** [comment]
> Hi @expoli , this is normal the rclone complains about there is no such plugin in that folder, after this, it will try to download the plugin. 
> 
> Have you tried to hit the `/rclone` from your browser to see if it works?

Yes I have tried, but it doesn't work 🤔, if I find some log, I will tell you

**Comment by wahyd4** [comment]
Please paste the full logs if you can

Kind regards,
Junwei Zhao

**Comment by expoli** [comment]
Sorry for taking so long to reply to you. When I tried to start the container today, I find I can't access the FileManger web and Other web pages are also similar to it.
1. The command
```
docker run -it --rm  --name aria2-ui -p 80:80 wahyd4/aria2-ui:arm64
```
2. The full logs:
```
**** update uid and gid to 1000:1000 ****
usermod: no changes
**** give caddy permissions to use low ports ****
forego        | starting filebrowser.1 on port 5000
forego        | starting caddy.1 on port 5100
forego        | starting aria2c.1 on port 5300
forego        | starting rclone.1 on port 5600
rclone.1      | Start Rclone
caddy.1       | Run aria2c and ariaNG
caddy.1       | Using caddy without Basic Auth
rclone.1      | 2020/12/04 04:51:34 ERROR : error reading available plugins: Error creating : /root/.cache/rclone/webgui/plugins/config
aria2c.1      | Start aria2 with standard mode
caddy.1       | {"level":"info","ts":1607057494.1996317,"logger":"automigrate","msg":"beginning one-time data directory migration","old_dir":"/root/.local/share/caddy","new_dir":"/app/.caddy/data/caddy","details":"https://github.com/caddyserver/caddy/issues/2955"}
caddy.1       | {"level":"error","ts":1607057494.2023256,"logger":"automigrate","msg":"new data directory already exists; skipping auto-migration as conservative safety measure - follow link for instructions","old_dir":"/root/.local/share/caddy","new_dir":"/app/.caddy/data/caddy","instructions":"https://github.com/caddyserver/caddy/issues/2955#issuecomment-570000333","error":"rename /root/.local/share/caddy /app/.caddy/data/caddy: permission denied"}
caddy.1       | {"level":"info","ts":1607057494.207972,"logger":"automigrate","msg":"successfully completed one-time migration of data directory","old_dir":"/root/.local/share/caddy","new_dir":"/app/.caddy/data/caddy","details":"https://github.com/caddyserver/caddy/issues/2955"}
caddy.1       | {"level":"info","ts":1607057494.2096782,"msg":"using provided configuration","config_file":"/usr/local/caddy/Caddyfile","config_adapter":"caddyfile"}
aria2c.1      | 
aria2c.1      | 12/04 04:51:34 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.
aria2c.1      | 
aria2c.1      | 12/04 04:51:34 [NOTICE] IPv4 RPC: listening on TCP port 6800
filebrowser.1 | 2020/12/04 04:51:34 No config file used
caddy.1       | {"level":"info","ts":1607057494.5935256,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["localhost:2019","[::1]:2019","127.0.0.1:2019"]}
caddy.1       | {"level":"info","ts":1607057494.595449,"logger":"http","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
caddy.1       | {"level":"info","ts":1607057494.5962527,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x4000418ee0"}
caddy.1       | {"level":"info","ts":1607057494.6006458,"logger":"tls","msg":"cleaned up storage units"}
caddy.1       | {"level":"info","ts":1607057494.6021,"msg":"autosaved config","file":"/app/.caddy/config/caddy/autosave.json"}
caddy.1       | {"level":"info","ts":1607057494.6021686,"msg":"serving initial configuration"}
filebrowser.1 | 2020/12/04 04:51:35 Listening on 127.0.0.1:8080
rclone.1      | 2020/12/04 04:51:36 NOTICE: A new release for gui is present at https://github.com/rclone/rclone-webui-react/releases/download/v2.0.3/currentbuild.zip
rclone.1      | 2020/12/04 04:51:36 NOTICE: Downloading webgui binary. Please wait. [Size: 4750769, Path :  /app/.cache/webgui/v2.0.3.zip]
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 
aria2c.1      | 12/04 04:51:44 [NOTICE] Serialized session to '/app/conf/aria2.session' successfully.
rclone.1      | 2020/12/04 04:51:50 NOTICE: Unzipping webgui binary
rclone.1      | 2020/12/04 04:51:51 NOTICE: Serving Web GUI
rclone.1      | 2020/12/04 04:51:51 NOTICE: Serving remote control on http://[::]:5572/
rclone.1      | 2020/12/04 04:51:51 NOTICE: Web GUI is not automatically opening browser. Navigate to http://user:password@[::]:5572/?login_token=dXNlcjpwYXNzd29yZA%3D%3D to use.
caddy.1       | {"level":"info","ts":1607057544.7499156,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.0.101:9118","proto":"HTTP/1.1","method":"GET","host":"192.168.0.100","uri":"/","headers":{"Accept-Language":["zh-CN,zh;q=0.9"],"Connection":["keep-alive"],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Encoding":["gzip, deflate"]}},"common_log":"192.168.0.101 - - [04/Dec/2020:04:52:24 +0000] \"GET / HTTP/1.1\" 0 0","duration":0.000013437,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
caddy.1       | {"level":"info","ts":1607057544.8688016,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.0.101:9118","proto":"HTTP/1.1","method":"GET","host":"192.168.0.100","uri":"/favicon.ico","headers":{"Referer":["http://192.168.0.100/"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["zh-CN,zh;q=0.9"],"Connection":["keep-alive"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"],"Dnt":["1"],"Accept":["image/avif,image/webp,image/apng,image/*,*/*;q=0.8"]}},"common_log":"192.168.0.101 - - [04/Dec/2020:04:52:24 +0000] \"GET /favicon.ico HTTP/1.1\" 0 0","duration":0.000012291,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
caddy.1       | {"level":"info","ts":1607057639.1271436,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.0.101:9182","proto":"HTTP/1.1","method":"GET","host":"192.168.0.100","uri":"/","headers":{"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.52"],"Connection":["keep-alive"],"Dnt":["1"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Accept-Encoding":["gzip, deflate"],"Accept-Language":["zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"],"Sec-Gpc":["1"]}},"common_log":"192.168.0.101 - - [04/Dec/2020:04:53:59 +0000] \"GET / HTTP/1.1\" 0 0","duration":0.000011406,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
caddy.1       | {"level":"info","ts":1607057641.3688858,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"192.168.0.101:9182","proto":"HTTP/1.1","method":"GET","host":"192.168.0.100","uri":"/favicon.ico","headers":{"Dnt":["1"],"Referer":["http://192.168.0.100/"],"Accept-Language":["zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6"],"Connection":["keep-alive"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.52"],"Accept":["image/webp,image/apng,image/*,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate"],"Sec-Gpc":["1"]}},"common_log":"192.168.0.101 - - [04/Dec/2020:04:54:01 +0000] \"GET /favicon.ico HTTP/1.1\" 0 0","duration":0.000012031,"size":0,"status":0,"resp_headers":{"Server":["Caddy"]}}
```

**Comment by wahyd4** [comment]
HI @expoli , from your logs I think everything is ok.  maybe try a different external port instead of `80`
```
docker run -it --rm  --name aria2-ui -p 8000:80 wahyd4/aria2-ui:arm64
```

**Pull request merged**
